# Generated by Django 5.1.7 on 2025-03-22 13:04

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('decription', ckeditor.fields.RichTextField()),
                ('sec_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.section')),
            ],
        ),
    ]
