# Generated by Django 5.1.7 on 2025-03-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(default=1, upload_to='food/'),
            preserve_default=False,
        ),
    ]
